name = "file-service"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
R2_ACCESS_KEY_ID = "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY = "${R2_SECRET_ACCESS_KEY}"
R2_END_POINT = "${R2_END_POINT}"
UPLOAD_TOKEN = "${UPLOAD_TOKEN}"
CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}"